In [7]:
import pandas as pd


def pandas_config(url_var1):
    """
    :param url_var1:
    :return:
    """
    var1 = pd.read_csv(url_var1)
    return var1


data = pandas_config("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/11-02-2021.csv")

In [8]:
data

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-11-03 06:22:09,33.93911,67.709953,156307,7281,NaN,NaN,Afghanistan,401.524946,4.658141
1,NaN,NaN,NaN,Albania,2021-11-03 06:22:09,41.15330,20.168300,186222,2937,NaN,NaN,Albania,6470.984780,1.577150
2,NaN,NaN,NaN,Algeria,2021-11-03 06:22:09,28.03390,1.659600,206649,5927,NaN,NaN,Algeria,471.252189,2.868148
3,NaN,NaN,NaN,Andorra,2021-11-03 06:22:09,42.50630,1.521800,15516,130,NaN,NaN,Andorra,20081.537566,0.837845
4,NaN,NaN,NaN,Angola,2021-11-03 06:22:09,-11.20270,17.873900,64487,1713,NaN,NaN,Angola,196.210291,2.656349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4011,NaN,NaN,Unknown,Ukraine,2021-11-03 06:22:09,NaN,NaN,0,0,0.0,0.0,"Unknown, Ukraine",0.000000,0.000000
4012,NaN,NaN,NaN,Nauru,2021-11-03 06:22:09,-0.52280,166.931500,0,0,0.0,0.0,Nauru,0.000000,0.000000
4013,NaN,NaN,Niue,New Zealand,2021-11-03 06:22:09,-19.05440,-169.867200,0,0,0.0,0.0,"Niue, New Zealand",0.000000,0.000000
4014,NaN,NaN,NaN,Tuvalu,2021-11-03 06:22:09,-7.10950,177.649300,0,0,0.0,0.0,Tuvalu,0.000000,0.000000
4015,NaN,NaN,Pitcairn Islands,United Kingdom,2021-11-03 06:22:09,-24.37680,-128.324200,0,0,0.0,0.0,"Pitcairn Islands, United Kingdom",0.000000,0.000000